# GET http://localhost:3000


### read json file

# GET http://localhost:4000/json

### create json file
GET http://localhost:5001/nodejsondb/file/create

### 
GET http://localhost:5001/nodejsondb/length

###
GET http://localhost:5001/nodejsondb/file/new

### get length of json file
GET http://localhost:5001/nodejsondb/length
