# GET http://localhost:3000


### read json file

# GET http://localhost:4000/json

### create files 
GET http://localhost:5011/nodejsondb/file/create

### 
GET http://localhost:5011/nodejsondb/import

## path
GET http://localhost:5011/nodejsondb/import

### Object_collection_stats create 
GET http://localhost:5011/nodejsondb/file/new

### Object_collection_stats create1 
GET http://localhost:5011/nodejsondb/file/new1


### get length of json file
GET http://localhost:5011/nodejsondb/length


### datasource file create
GET http://localhost:5011/nodejsondb/datasource

### modifiy file
GET http://localhost:5011/nodejsondb/modifiedFiles


### modifiy file1
GET http://localhost:5011/nodejsondb/modifiedFiles1
